apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      # Clone the Git repository that contains the Kustomize configuration
      # to the ./repository directory.
      - uses: git-clone
        config:
          repoURL: https://github.com/hiddeco/kargo-simple-new.git
          checkout:
          - branch: kustomize
            path: ./repository
      # Update the image in the Kustomize configuration located at ./env/dev
      # in the repository.
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./repository/env/dev
          images:
          - image: ghcr.io/hiddeco/guestbook
      # Commit the changes to the Git repository.
      - uses: git-commit
        as: commit
        config:
          path: ./repository
          messageFromSteps:
          - update-image
      # Push the changes to the Git repository.
      - uses: git-push
        config:
          path: ./repository
      # If you have an Argo CD Application that should be synced after the Git
      # repository is updated, uncomment the following lines and specify the
      # app name.
      # - uses: argocd-update
      #   config:
      #     apps:
      #     - name: guestbook-dev
      #       sources:
      #       - repoURL: https://github.com/hiddeco/kargo-simple-new.git
      #         desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - dev
  promotionTemplate:
    spec:
      steps:
      # Clone the Git repository that contains the Kustomize configuration
      # to the ./repository directory.
      - uses: git-clone
        config:
          repoURL: https://github.com/hiddeco/kargo-simple-new.git
          checkout:
          - branch: kustomize
            path: ./repository
      # Update the image in the Kustomize configuration located at ./env/staging
      # in the repository.
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./repository/env/staging
          images:
          - image: ghcr.io/hiddeco/guestbook
      # Commit the changes to the Git repository.
      - uses: git-commit
        as: commit
        config:
          path: ./repository
          messageFromSteps:
          - update-image
      # Push the changes to the Git repository.
      - uses: git-push
        config:
          path: ./repository
      # If you have an Argo CD Application that should be synced after the Git
      # repository is updated, uncomment the following lines and specify the
      # app name.
      # - uses: argocd-update
      #   config:
      #     apps:
      #       - name: guestbook-staging
      #         sources:
      #         - repoURL: https://github.com/hiddeco/kargo-simple-new.git
      #           desiredCommitFromStep: commit
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-simple
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: guestbook
    sources:
      direct: false
      stages:
        - staging
  promotionTemplate:
    spec:
      steps:
      # Clone the Git repository that contains the Kustomize configuration
      # to the ./repository directory.
      - uses: git-clone
        config:
          repoURL: https://github.com/hiddeco/kargo-simple-new.git
          checkout:
            - branch: kustomize
              path: ./repository
      # Update the image in the Kustomize configuration located at ./env/prod
      # in the repository.
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./repository/env/prod
          images:
          - image: ghcr.io/hiddeco/guestbook
      # Commit the changes to the Git repository.
      - uses: git-commit
        as: commit
        config:
          path: ./repository
          messageFromSteps:
          - update-image
      # Push the changes to the Git repository.
      - uses: git-push
        config:
          path: ./repository
      # If you have an Argo CD Application that should be synced after the Git
      # repository is updated, uncomment the following lines and specify the
      # app name.
      # - uses: argocd-update
      #   config:
      #     apps:
      #     - name: guestbook-prod
      #       sources:
      #       - repoURL: https://github.com/hiddeco/kargo-simple-new.git
      #         desiredCommitFromStep: commit
